# Generated by Django 5.1.5 on 2025-03-06 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0002_addressmodel_state"),
        ("orders", "0002_ordermodel_active_ordermodel_billing_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="billing_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_address",
                to="address.addressmodel",
            ),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_address",
                to="address.addressmodel",
            ),
        ),
    ]
