# Generated by Django 5.1.5 on 2025-03-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="addressmodel",
            name="state",
            field=models.CharField(default="Maharashtra", max_length=120),
        ),
    ]
