# Generated by Django 5.1.5 on 2025-02-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_productmodel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
