# Generated by Django 5.1.5 on 2025-02-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartmodel",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
