# Generated by Django 5.1.5 on 2025-02-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0018_productmodel_timestamp"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagmodel",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="tag", to="products.productmodel"
            ),
        ),
    ]
