# Generated by Django 5.1.5 on 2025-02-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_productmodel_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="products/"),
        ),
    ]
