# Generated by Django 5.1.5 on 2025-02-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_productmodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="upload_image_path"
            ),
        ),
    ]
