# Generated by Django 5.1.5 on 2025-02-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_alter_productmodel_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
