# Generated by Django 5.1.5 on 2025-02-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="price",
            field=models.DecimalField(decimal_places=2, default=39.99, max_digits=20),
        ),
    ]
