# Generated by Django 5.1.5 on 2025-02-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_productmodel_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="slug",
            field=models.SlugField(default="abc"),
            preserve_default=False,
        ),
    ]
